services:
  bot:
    build: .
    volumes:
      - ./.env:/app/.env:ro
      - ./backgrounds:/app/backgrounds
      - ./fonts:/app/fonts
      - ./video:/app/video
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
